name: Flutter Web CI/CD

on:
  push:
    branches:
      - master  # El flujo de trabajo se ejecutará en cada push a la rama principal
  pull_request:
    branches:
      - master  # También se ejecutará en cada pull request hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release --base-href="/"

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Upload to S3
      run: |
        aws s3 sync build/web s3://$AWS_S3_BUCKET/ --exact-timestamps --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}